import { motion } from 'framer-motion'
import { FileText } from 'lucide-react'
import SEO from '../components/common/SEO'

const Section = ({ title, children }) => (
  <section className="mb-8">
    <h2 className="text-lg font-bold text-white mb-3">{title}</h2>
    <div className="text-sm text-zinc-400 leading-relaxed space-y-3">{children}</div>
  </section>
)

export default function Terms() {
  return (
    <>
      <SEO
        title="Terms & Conditions — ToolForge"
        description="Read ToolForge's terms and conditions. Understand the rules governing your use of our free online tools and services."
        keywords="toolforge terms and conditions, terms of service, user agreement"
      />
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-16">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          <div className="flex items-center gap-3 mb-3">
            <FileText className="w-7 h-7 text-teal-400" />
            <h1 className="text-3xl font-bold text-white">Terms & Conditions</h1>
          </div>
          <p className="text-sm text-zinc-500 mb-10">Last updated: January 1, 2025</p>

          <Section title="1. Acceptance of Terms">
            <p>By accessing and using ToolForge ("the Service"), you agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use our service. We reserve the right to update these terms at any time, and continued use constitutes acceptance of any changes.</p>
          </Section>

          <Section title="2. Description of Service">
            <p>ToolForge provides free online tools for image compression, PDF conversion, text summarization, resume analysis, caption generation, and related tasks. The service is provided "as is" and may be modified, suspended, or discontinued at any time without notice.</p>
          </Section>

          <Section title="3. Acceptable Use">
            <p>You agree NOT to use ToolForge to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Upload illegal, harmful, obscene, or copyrighted content you don't have rights to</li>
              <li>Attempt to reverse-engineer, exploit, or compromise our systems</li>
              <li>Use automated bots or scripts to abuse our tools</li>
              <li>Upload malware, viruses, or malicious code</li>
              <li>Violate any applicable local, national, or international law</li>
              <li>Upload content involving minors in any inappropriate context</li>
            </ul>
            <p>Violation of these terms may result in permanent IP banning and, where applicable, reporting to authorities.</p>
          </Section>

          <Section title="4. Intellectual Property">
            <p>The ToolForge name, logo, design, and original code are our intellectual property. You retain all rights to files you upload and process through our service. We claim no ownership over your content. Results generated by our tools are yours to use freely.</p>
          </Section>

          <Section title="5. Disclaimer of Warranties">
            <p>ToolForge is provided on an "AS IS" and "AS AVAILABLE" basis without warranties of any kind, either express or implied. We do not warrant that the service will be uninterrupted, error-free, or completely secure. Tool results (especially AI-generated content like ATS scores and captions) are for informational purposes and should not be solely relied upon for critical decisions.</p>
          </Section>

          <Section title="6. Limitation of Liability">
            <p>To the maximum extent permitted by law, ToolForge shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, goodwill, or other intangible losses resulting from your use or inability to use the service. Our total liability shall not exceed $10 USD.</p>
          </Section>

          <Section title="7. File Upload Policy">
            <p>By uploading files to ToolForge, you confirm that: (a) you have the right to process those files, (b) the files do not contain illegal content, and (c) you understand files will be automatically deleted within 1 hour of processing. We are not responsible for any data loss that may occur during this process.</p>
          </Section>

          <Section title="8. Advertising and Affiliates">
            <p>ToolForge displays advertisements through Google AdSense and other networks. We also include affiliate links that may generate commission when clicked and purchased. All advertising and affiliate relationships are disclosed as required by applicable law and FTC guidelines.</p>
          </Section>

          <Section title="9. Third-Party Services">
            <p>Our service may contain links to third-party websites and services. We are not responsible for the content, privacy practices, or terms of those third parties. Use of third-party services is governed by their respective terms and conditions.</p>
          </Section>

          <Section title="10. Governing Law">
            <p>These terms shall be governed by and construed in accordance with applicable laws. Any disputes arising from these terms or use of the service shall be subject to the exclusive jurisdiction of competent courts.</p>
          </Section>

          <Section title="11. Contact">
            <p>For questions about these Terms and Conditions, contact us at:<br />
              <strong className="text-zinc-300">Email:</strong> legal@toolforge.app
            </p>
          </Section>
        </motion.div>
      </div>
    </>
  )
}
