import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Download, Share2, Sparkles, RefreshCw, Image } from 'lucide-react'
import toast from 'react-hot-toast'
import axios from 'axios'
import SEO from '../../components/common/SEO'

const categories = [
  { key: 'motivation', label: '💪 Motivation', emoji: '💪' },
  { key: 'love', label: '❤️ Love', emoji: '❤️' },
  { key: 'sad', label: '😢 Sad', emoji: '😢' },
  { key: 'life', label: '🌿 Life', emoji: '🌿' },
  { key: 'success', label: '🏆 Success', emoji: '🏆' },
]

export default function TamilQuoteGenerator() {
  const [selected, setSelected] = useState('motivation')
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState(null)

  const generate = async () => {
    setLoading(true)
    setResult(null)
    try {
      const { data } = await axios.post('/api/tamil-quote/generate', { keyword: selected })
      if (data.success) {
        setResult(data)
        toast.success('Quote image ready!')
      }
    } catch (err) {
      toast.error('Generation failed. Try again!')
    } finally {
      setLoading(false)
    }
  }

  const download = async () => {
    if (!result) return
    try {
      const response = await fetch(result.imageUrl)
      const blob = await response.blob()
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `tamil-quote-${selected}-${Date.now()}.png`
      a.click()
      URL.revokeObjectURL(url)
      toast.success('Downloaded!')
    } catch {
      toast.error('Download failed')
    }
  }

  const shareWhatsApp = () => {
    if (!result) return
    const text = `${result.quote}\n\n— ${result.author}\n\nGenerated by ToolForge.app`
    const url = `https://wa.me/?text=${encodeURIComponent(text)}`
    window.open(url, '_blank')
  }

  return (
    <>
      <SEO
        title="Tamil Quote Image Generator - ToolForge"
        description="Generate beautiful Tamil quote images for WhatsApp, Instagram & more. Choose love, motivation, sad quotes with stylish backgrounds."
        keywords="tamil quote generator, tamil quotes images, whatsapp tamil quotes, motivation quotes tamil"
      />

      <div className="min-h-screen py-12 px-4">
        <div className="max-w-2xl mx-auto">

          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-center mb-10"
          >
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass mb-4 text-sm text-teal-400">
              <Sparkles className="w-4 h-4" />
              Tamil Quote Generator
            </div>
            <h1 className="text-4xl font-bold mb-3">
              <span className="gradient-text">Tamil Quote</span> Image Generator
            </h1>
            <p className="text-zinc-400 text-lg">
              Beautiful Tamil quotes with stylish backgrounds — Download & Share instantly
            </p>
          </motion.div>

          {/* Category Selector */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="glass rounded-2xl p-6 mb-6"
          >
            <p className="text-sm text-zinc-400 mb-4 font-medium">Select Quote Category:</p>
            <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
              {categories.map(cat => (
                <button
                  key={cat.key}
                  onClick={() => setSelected(cat.key)}
                  className={`py-3 px-2 rounded-xl text-sm font-medium transition-all duration-200 text-center ${
                    selected === cat.key
                      ? 'bg-teal-500/20 border border-teal-500/50 text-teal-400'
                      : 'glass border border-white/5 text-zinc-400 hover:text-white hover:bg-white/5'
                  }`}
                >
                  <div className="text-xl mb-1">{cat.emoji}</div>
                  <div className="text-xs">{cat.key.charAt(0).toUpperCase() + cat.key.slice(1)}</div>
                </button>
              ))}
            </div>
          </motion.div>

          {/* Generate Button */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="mb-6"
          >
            <button
              onClick={generate}
              disabled={loading}
              className="w-full btn-primary py-4 text-lg flex items-center justify-center gap-3 disabled:opacity-50"
            >
              {loading ? (
                <>
                  <RefreshCw className="w-5 h-5 animate-spin" />
                  Generating Image...
                </>
              ) : (
                <>
                  <Sparkles className="w-5 h-5" />
                  Generate Tamil Quote Image
                </>
              )}
            </button>
          </motion.div>

          {/* Result */}
          <AnimatePresence>
            {result && (
              <motion.div
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.95 }}
                className="glass rounded-2xl overflow-hidden"
              >
                {/* Quote Text Preview */}
                <div className="p-5 border-b border-white/5">
                  <p className="text-white text-lg font-medium leading-relaxed mb-2">
                    "{result.quote}"
                  </p>
                  <p className="text-teal-400 text-sm">— {result.author}</p>
                </div>

                {/* Image Preview */}
                <div className="relative bg-zinc-900">
                  <img
                    src={result.imageUrl}
                    alt="Tamil Quote"
                    className="w-full rounded-none"
                    loading="lazy"
                  />
                  <div className="absolute top-3 right-3">
                    <span className="px-2 py-1 rounded-lg bg-black/50 text-xs text-white">
                      800×800px
                    </span>
                  </div>
                </div>

                {/* Action Buttons */}
                <div className="p-5 grid grid-cols-2 gap-3">
                  <button
                    onClick={download}
                    className="btn-primary flex items-center justify-center gap-2 py-3"
                  >
                    <Download className="w-4 h-4" />
                    Download PNG
                  </button>
                  <button
                    onClick={shareWhatsApp}
                    className="flex items-center justify-center gap-2 py-3 px-4 rounded-xl font-medium text-sm transition-all"
                    style={{ background: '#25D366', color: 'white' }}
                  >
                    <Share2 className="w-4 h-4" />
                    Share on WhatsApp
                  </button>
                </div>

                {/* Generate Another */}
                <div className="px-5 pb-5">
                  <button
                    onClick={generate}
                    className="w-full py-3 rounded-xl glass border border-white/10 text-zinc-400 hover:text-white text-sm flex items-center justify-center gap-2 transition-all"
                  >
                    <RefreshCw className="w-4 h-4" />
                    Generate Another Quote
                  </button>
                </div>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Empty State */}
          {!result && !loading && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="glass rounded-2xl p-12 text-center"
            >
              <Image className="w-12 h-12 text-zinc-600 mx-auto mb-4" />
              <p className="text-zinc-500 text-sm">
                Select a category and click Generate to create your Tamil quote image
              </p>
            </motion.div>
          )}

          {/* Info Cards */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.3 }}
            className="mt-8 grid grid-cols-3 gap-4"
          >
            {[
              { icon: '🖼️', label: 'HD Quality', desc: '800×800 PNG' },
              { icon: '📱', label: 'WhatsApp Ready', desc: 'Perfect size' },
              { icon: '⚡', label: 'Instant', desc: 'No wait time' },
            ].map((item) => (
              <div key={item.label} className="glass rounded-xl p-4 text-center">
                <div className="text-2xl mb-2">{item.icon}</div>
                <div className="text-xs font-medium text-white">{item.label}</div>
                <div className="text-xs text-zinc-500">{item.desc}</div>
              </div>
            ))}
          </motion.div>
        </div>
      </div>
    </>
  )
}
